Allow HttpConfiguration to Jetty server
logzio/guice-jersey pull request #27
Opened 2021-03-14 15:36 UTC by ohadza

2021-03-15 15:45 UTC, asafalima approved these changes

2021-03-15 15:47 UTC, asafm requested changes
Let's also create a release - change version to 0.13

2021-03-15 15:47 UTC, asafm commented on src/main/java/io/logz/guice/jersey/JerseyServer.java
> +            ServerConnector connector = new ServerConnector(server, new HttpConnectionFactory(configuration.getHttpConfiguration()));
let's do this like the rest:
```
connector.setConnectionFactories(new HttpConnectionFactory(configuration.getHttpConfiguration()))
```

2021-03-15 15:47 UTC, asafm commented on src/main/java/io/logz/guice/jersey/configuration/JerseyConfigurationBuilder.java
> +    public JerseyConfigurationBuilder addPortWithHttpConfiguration(int port, HttpConfiguration httpConfiguration) {
It's too many flavors. Let's create a `ServerConnectorConfigurationBuilder` and do this right

2021-03-15 15:47 UTC, asafm commented on src/test/java/io/logz/guice/jersey/supplier/JerseyServerSupplier.java
> +        configurationBuilder.addPortWithHttpConfiguration(port, new HttpConfiguration());
Let's add a small test that shows I configure jetty with it and it works. Max request header sounds about right

2021-03-16 09:11 UTC, asafm approved these changes

2021-03-16 09:28 UTC, merged